### ISSUE TITLE
Sudden Data Jumps in AS5600 Encoder Readings

### ISSUE THREAD

**Issue by ewecan** [SaraEye/SaraKIT-Python-Examples#1]
When I use the AS5600 encoder, I found that when running "TestEncoder.py," the data suddenly jumps from one value to another at a certain point. For example, when the motor rotates from 0 to 8.07, it suddenly changes to 0.47. Is this caused by the encoder? How can this be resolved?

**Comment by ArturMajtczak** [comment]
https://sarakit.saraai.com/community/faq
(Q: My AS5600 encoder is not working. What should I do?)
(Q: My encoder does not display the full 360-degree angle (360° = 2*Pi = 6.2831 rad) or skips certain values. What should I do?)
